// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    BreadCurmb: typeof import('./src/components/BreadCurmb.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Footter: typeof import('./src/components/Footter.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle/ThemeToggler.vue')['default']
    ThemeToggler: typeof import('./src/components/ThemeToggler.vue')['default']
  }

}
